### ISSUE TITLE
Failed to initialize many to many

### ISSUE THREAD

**Issue by StefanoLambiase** [StefanoLambiase/biblionet#32]
L'inizializzazione di un oggetto di tipo Lettore non inserisce nell'oggetto le variabili annotate come manyToMany. Questo rende impossibile andare a stampare i valori dei generi conosciuti da un lettore perché non presenti.

Di seguito l'errore dato: "failed to lazily initialize a collection of role"

**Comment by BearGrillz99** [comment]
Aggiungere accanto alle annotazioni ManyToMany oppure OneToMany la seguente annotazione: (fetch = FetchType.EAGER)

https://stackoverflow.com/questions/22821695/how-to-fix-hibernate-lazyinitializationexception-failed-to-lazily-initialize-a
