### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Tekhorror** [StefanoLambiase/biblionet#74]
La pagina di registrazione dell'esperto non ha il titolo  Rsiolto
La home attende le modifiche attualmente sul branch dell'aggiunta libro Risolto 
Il background in layout va cambiato da ffffff a f2f2f2  Risolto
Nella lista dei club del libro il tasto crea club del Libro e modifica la scritta va cambiata da nero a bianco. Risolto
Il tasto contatta nel club del libro, scritta in nero. Risolto
Il tasto visualizza club per l'esperto non funziona nell'area utente Risolto
Il tasto visualizza Ticket non funziona nell'area utente. In attesa di Alessio praticamente .Risolto
Scritte sulle immagini della home Risolto
(Tutte le cose risolte sono state fatte da Alessio Casolaro).
Ancora aperte
Nella visualizzazione lista esperti (comunicazione con esperto) aggiungere tasto contatta esperto.
Il tasto "Esperti " nella home che dovrebbe rimandare alla lista degli esperti non funziona

**Comment by atdepo** [comment]
Visualizzazione lista esperti risolto
